name: G9_exp

on:
  push:
    branches:
      - G9_exp

jobs:
  build-proton-ge:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.1
    
      - name: Clone repo
        run: git clone -b ${{ steps.branch-name.outputs.current_branch }} --jobs 20 --recurse-submodules ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} .

      - name: Get Proton Versions
        run: echo "RELEASE_VERSION=$(cat VERSION)" >> $GITHUB_ENV
        
      - name: Display version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Setup multiarch
        run: sudo dpkg --add-architecture i386

      - name: Install dependencies apt
        run: sudo apt update -y && sudo apt-get install -y ccache fontforge-nox

      - name: Install dependencies gallium nine
        run: >
          sudo apt-get install -y
          gcc-multilib
          libc6-dev:i386
          meson
          libwine
          libwine:i386
          libwine-dev
          libdrm-dev
          libdrm-dev:i386
          libx11-xcb-dev
          libx11-xcb-dev:i386
          libxcb-present-dev
          libxcb-present-dev:i386
          libxcb-dri3-dev
          libxcb-dri3-dev:i386
          libxcb-dri2-0-dev
          libxcb-dri2-0-dev:i386
          libegl1-mesa-dev
          libegl1-mesa-dev:i386
          libgl1-mesa-dev
          libgl1-mesa-dev:i386
          libd3dadapter9-mesa-dev
          libd3dadapter9-mesa-dev:i386
      
      - name: Install dependencies workaround gallium nine
        run: |
          # libwine-dev and libwine-dev:i386 conflict with each other
          # copy the native 64bit one to /tmp, which also avoids a winegcc multiarch bug
          sudo cp -av /usr/lib/x86_64-linux-gnu/wine /tmp/wine64
          sudo apt-get install -y libwine-dev:i386

      - name: apply patches
        run: ./patches/protonprep-valve-staging.sh  || true

      - name: Create dir structure
        run: mkdir build

      - name: Create/Download ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ccache-proton-${{ github.run_id }}
          restore-keys: |
            ccache-proton

      - name: Configure build proton
        working-directory: ./build/
        run: ../configure.sh --build-name="${{ env.RELEASE_VERSION }}" --enable-ccache

      - name: Compile Gallium Nine
        env:
          WINE64_LIBDIR: /tmp/wine64
          WINE32_LIBDIR: /usr/lib/i386-linux-gnu/wine
        working-directory: ./wine-nine-standalone/
        run: ./release.sh -o "g9_temp" -- -Ddri2=true -Ddistro-independent=true

      # Build name following convention: Proton-<tag>
      - name: Build proton
        working-directory: ./build/
        run: make dist

      - name: Rename directory
        working-directory: ./build/
        run: mv dist ${{ env.RELEASE_VERSION }}

      - name: Move files to their right folder
        working-directory: ./build/${{ env.RELEASE_VERSION }}/protonfixes/
        run: |
          mv cabextract ../files/bin/ && \
          mv libmspack.so.0 ../files/lib64/ && \
          mv libmspack.so.0.1.0 ../files/lib64/ && \
          rm cabextract_1.9-1.debian.tar.xz libmspack_0.10.1-1.debian.tar.xz

      - name: Copy gallium nine output file
        run: |
          mkdir ./build/${{ env.RELEASE_VERSION }}/files/lib64/wine/galliumnine/
          mkdir ./build/${{ env.RELEASE_VERSION }}/files/lib/wine/galliumnine/
          cp -f ./wine-nine-standalone/gallium-nine-standalone/lib64/d3d9-nine.dll.so ./build/${{ env.RELEASE_VERSION }}/files/lib64/wine/galliumnine/d3d9-nine.dll
          cp -f ./wine-nine-standalone/gallium-nine-standalone/lib32/d3d9-nine.dll.so ./build/${{ env.RELEASE_VERSION }}/files/lib/wine/galliumnine/d3d9-nine.dll
          cp -f ./wine-nine-standalone/gallium-nine-standalone/bin64/ninewinecfg.exe.so ./build/${{ env.RELEASE_VERSION }}/files/lib64/wine/galliumnine/ninewinecfg.exe
          cp -f ./wine-nine-standalone/gallium-nine-standalone/bin32/ninewinecfg.exe.so ./build/${{ env.RELEASE_VERSION }}/files/lib/wine/galliumnine/ninewinecfg.exe

      - name: Archive build
        working-directory: ./build/
        run: tar -czvf ${{ env.RELEASE_VERSION }}-G9.tar.gz ${{ env.RELEASE_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RELEASE_VERSION }}-G9
          path: build/${{ env.RELEASE_VERSION }}-G9.tar.gz
